insert into shows (name, id) values ('Arrow',257655)
insert into shows (name, id) values ('Riverdale',311954)
insert into shows (name, id) values ('The Librarians',281709)
insert into shows (name, id) values ('The Big Bang Theory',80379)
insert into shows (name, id) values ('Marvels Agents of Shield',263365)
insert into shows (name, id) values ('Blindspot',295647)
insert into shows (name, id) values ('Supernatural',78901)
insert into shows (name, id) values ('Star Tek: Discovery',328711)
insert into shows (name, id) values ('The Flash',279121)
insert into shows (name, id) values ('Mobile Suit Gundam Iron-blooded orphans',299497)
insert into shows (name, id) values ('Modern Family',95011)
insert into shows (name, id) values ('Lucifer',295685)
insert into shows (name, id) values ('The Walking Dead',153021)
insert into shows (name, id) values ('Strike Back',148581)
insert into shows (name, id) values ('Brooklyn Nine Nine',269586)
insert into shows (name, id) values ('The Gifted',328552)
insert into shows (name, id) values ('Gotham',274431)
insert into shows (name, id) values ('DCs Legends of Tomorrow',295760)